# Generated by Django 5.1.4 on 2024-12-21 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auction_bid_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='image_url',
            field=models.URLField(default=None),
        ),
        migrations.AlterField(
            model_name='auction',
            name='description',
            field=models.TextField(),
        ),
    ]
