# Generated by Django 5.1.4 on 2024-12-21 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auction_image_url_alter_auction_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='image_url',
            new_name='img_url',
        ),
    ]
