# Generated by Django 5.1.4 on 2024-12-23 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_alter_comment_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='img_url',
            field=models.URLField(blank=True, default='https://github.com/joanne5548/cs50-projects/blob/main/commerce/auctions/static/auctions/assets/default_image.png?raw=true'),
        ),
    ]
