# Generated by Django 5.1.4 on 2024-12-26 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_alter_auction_img_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='starting_bid',
            new_name='highest_bid',
        ),
        migrations.RemoveField(
            model_name='auction',
            name='closing_bid',
        ),
    ]
